Use pandas console-friendly to_string() output instead of HTML output
The previous approach of installing `pandas-profiling` doesn't work for some reason (even though a manual install of that lib in the notebook was working previously), therefore the other alternative is to avoid HTML formatting the output entirely when printing the results.

Wrapping the Pandas `DataFrame` in a `print()` will pick up a different
formatter and avoid the issue shown below:

```
/usr/local/lib/python3.7/dist-packages/pandas/io/formats/format.py in to_html(self, buf, encoding, classes, notebook, border)
    986         notebook : {True, False}, optional, default False
    987             Whether the generated HTML is for IPython Notebook.
--> 988         border : int
    989             A ``border=border`` attribute is included in the opening
    990             ``<table>`` tag. Default ``pd.options.display.html.border``.

AttributeError: 'NotebookFormatter' object has no attribute 'get_result'
```